import { type StudioDoc, listRules } from "./doc"
import { getToken, recipeStyles, recipes, styleKey } from "./theme-meta"

/**
 * Serializes a studio document as a Panda preset that extends `@isbatak/panda-ds`. Panda deep-merges
 * `theme.extend`, so only the edited tokens and recipe declarations need to be emitted.
 */

type Dict = Record<string, any>

function setPath(target: Dict, path: string[], value: unknown) {
  let node = target
  for (const segment of path.slice(0, -1)) {
    node[segment] ??= {}
    node = node[segment]
  }
  node[path.at(-1)!] = value
}

function tokenPath(key: string) {
  const [category, ...rest] = key.split(".")
  const token = getToken(category!, rest.join("."))
  return [category!, ...(token?.path ?? rest)]
}

export function toPresetObject(doc: StudioDoc) {
  const extend: Dict = {}

  for (const [key, value] of Object.entries(doc.tokens)) {
    setPath(extend, ["tokens", ...tokenPath(key), "value"], value)
  }

  for (const [key, value] of Object.entries(doc.semanticTokens)) {
    const [category, ...rest] = key.split(".")
    const original = getToken(category!, rest.join("."))?.value
    // Keep the conditions that weren't edited, since `value` is replaced as a whole
    const merged = { ...(typeof original === "object" ? original : { base: original }), ...value }
    const path = tokenPath(key)
    setPath(extend, ["semanticTokens", ...path, "value"], merged)
  }

  for (const rule of listRules(doc)) {
    const recipe = recipes[rule.recipe]
    if (!recipe) continue
    const group = recipe.slots ? "slotRecipes" : "recipes"
    const scopePath = rule.scope === "base" ? ["base"] : ["variants", ...rule.scope.split(":")]
    const path = [group, rule.recipe, ...scopePath, ...(rule.slot ? [rule.slot] : [])]
    if (rule.state) path.push(`_${rule.state}`)
    const key = styleKey(recipeStyles(recipe, rule.scope, rule.slot), rule.property, rule.state)
    setPath(extend, [...path, key], rule.value)
  }

  return extend
}

export function toPresetSource(doc: StudioDoc, name = "panda-studio") {
  const body = JSON.stringify({ name, theme: { extend: toPresetObject(doc) } }, null, 2)
    // Unquote keys that are valid identifiers to match hand-written Panda configs
    .replace(/^(\s*)"([A-Za-z_$][\w$]*)":/gm, "$1$2:")
  return `import { definePreset } from "@pandacss/dev"

/**
 * Generated by Panda Studio. Add it to the \`presets\` of a Panda config that uses \`@isbatak/panda-ds\`.
 */
export const studioPreset = definePreset(${body})
`
}
